name = "cf02-sub"
main = "_worker.js"
compatibility_date = "2025-07-23"
keep_vars = true

#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改

#id = "4fcb6d74f5a3464bb123ba8e5efcb54d"					#KV据库id

